FROM emsusignage.azurecr.io/python_base:0.0.1-amd64

WORKDIR /app

COPY ./requirements.txt ./
RUN pip install -r requirements.txt

COPY . .

EXPOSE 8080

CMD [ "python3", "-u", "./__main__.py", "-p 8080" ]

